
pub const NETGRASP_TITLE_TEMPLATE: &str = "[netgrasp] {{event}}: {{device}}";

pub const NETGRASP_TEXT_TEMPLATE: &str = "{{notification}}:
 * {{name}} {{wrapped_vendor}}
 * ip: {{ip}} [{{mac}}]
 * interface: {{interface}}
 * previously seen: {{previously_seen}}
 * first seen: {{first_seen}}
 * recently seen: {{recently_seen}}

In the past 24 hours, this device talked to {{devices_talked_to_count}} {{device_string}}.

--
Email generated by the Netgrasp passive network observation tool.
https://github.com/jeremyandrews/netgrasp";

pub const NETGRASP_HTML_TEMPLATE: &str = r#"
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<HTML lang={{lang}}>
<HEAD></HEAD>
<BODY>
  <P>{{notification}}:</P>
  <UL>
    <LI>{{name}} <EM>{{wrapped_vendor}}</EM>
    <LI>ip: {{ip}} [{{mac}}]</LI>
    <LI>interface: {{interface}}</LI>
    <LI>previously seen: {{previously_seen}}</LI>
    <LI>first seen: {{first_seen}}</LI>
    <LI>recently seen: {{recently_seen}}</LI>
  </UL>
  <P>In the past 24 hours, this device talked to {{devices_talked_to_count}} {{device_string}}.</P>
  <DIV ID="footer">
    <HR />
    <P><SMALL><EM>Email generated by the <A HREF="https://github.com/jeremyandrews/netgrasp">Netgrasp</A> passive network observation tool.</EM></SMALL></P>
  </DIV>
</BODY>
</HTML>"#;